# Generated by Django 3.2.7 on 2021-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('country', models.CharField(max_length=10, verbose_name='Country')),
                ('open_weather_id', models.IntegerField(verbose_name='Open Weather ID')),
            ],
            options={
                'verbose_name': 'Open Weather City',
                'verbose_name_plural': 'Open Weather Cities',
            },
        ),
    ]
